"""Added placed field to Students

Revision ID: 4f7f40c18c57
Revises: d7b48b3e6049
Create Date: 2025-02-27 11:47:35.231543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7f40c18c57'
down_revision = 'd7b48b3e6049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('placed')

    # ### end Alembic commands ###
