"""Fix student_id foreign key in batch_students

Revision ID: d7b48b3e6049
Revises: a1f713712389
Create Date: 2025-02-21 15:51:16.207124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7b48b3e6049'
down_revision = 'a1f713712389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_students', schema=None) as batch_op:
        batch_op.alter_column('batch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('batch_students_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('batch_students_ibfk_2', 'users', ['student_id'], ['id'])
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('batch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
